name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: pkthedeveloper22
          outputs: dist/github-contribution-grid-snake.svg
